export const listaDeUsuarios = [
  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},
  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},
  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},
  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},
  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},
  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},

  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},
  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444},

  {name: 'terry', dni: 111},
  {name: 'dariem', dni: 222},
  {name: 'gerrard', dni: 333},
  {name: 'bryan', dni: 444}
]